### ISSUE TITLE
Append Host in Group

### ISSUE THREAD

**Issue by EniotnaTennob** [CheckPointSW/CheckPointAnsibleMgmtCollection#29]
Hello
With the previous version of check_point_mgmt, we could append member to a group by using set-group command

> check_point_mgmt:
&nbsp;&nbsp;command: **set-group**
&nbsp;&nbsp;parameters:
&nbsp;&nbsp;&nbsp;&nbsp;name: MyHost_Group
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;members:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**add:**
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- MyHost_Name

And this currently seems impossible (add argument to members no longer recognized for check_point.mgmt.cp_mgmt_group), when we add one member in a group, all other members present before disappear.

Is it possible to fix this issue, please ?

**Comment by chkp-orso** [comment]
Hi,

Thanks for reaching us.

Hi,

I will sum it up.

In the API in many "set" commands (e.g. set-group), when there is a parameter of type "list" (e.g. members) there are 4 options of value the list can get: add/remove/string/list:string

We intentionally removed the first three options because it damages one of Ansible requirements for idempotency.

But it's still possible to add/remove an element from list (members) by supplying the whole list with/except the elements you want to add/remove. 

Thanks,
Or
