### ISSUE TITLE
Check for missing commits vs devel

### ISSUE THREAD

**Issue by gundalow** [CheckPointSW/CheckPointAnsibleMgmtCollection#6]
##### SUMMARY
The "Big Migration" has now taken place.

As this collection already exists, we need to carefully check to see if any further commits went into devel since this repo was created.

Please check the contents of https://github.com/ansible-collection-migration/check_point.mgmt against this repo

In particular:
* Please do a per-file level diff against every file in the ansible-collection-migration repo and this one
* Pay care to files added and removed.
* During the last two weeks there have been lots of fixes, especially around and tests, dependencies, and new collection features e.g. meta/action_groups.yml

##### ISSUE TYPE
- Bug Report

**Comment by chkp-orso** [comment]
Hi @gundalow 

1. there is difference in the file `checkpoint.py` in `CheckPointAnsibleMgmtCollection/plugins/module_utils/` (in our repo)
2. I saw you removed `__metaclass__ = type` in the above file. why is that? should I remove it?
3. In our repo the folder under `tests` called `units` and in your repo it's called `unit`
4. Is our repo will be relevant any more?
5. If it does relevant, should I change it to looks like your repo?
5. How could I push fixes to the new repo, should I open a PR, or will I get access to it?
6. The README is different
7. The galaxy.yml is different. especially those fields: version, authors, description
8. I saw a lot of different imports, but I assume it's OK because it's derived from a different directories hierarchy

Thanks, Or

**Comment by justjais** [comment]
@chkp-orso as discussed yesterday, the above repo was created from Ansible partner engineering team, so the respective repo would be archived and the queries you've put forward changes are also needed in the CP collection repo.

So, you can go ahead and close the respective issue. Thanks

**Comment by chkp-orso** [comment]
@justjais Thanks Sumit :)
